
import streamlit as st
import pandas as pd
import altair as alt
import numpy as np

from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from mlxtend.frequent_patterns import apriori, association_rules

st.set_page_config(page_title="Saxbys Purchase Dashboard", layout="wide")

st.title("☕ Saxbys Purchase Dashboard")
st.caption("Dashboard generated by dashboard_agent.py from processed transaction and category files.")


TRANSACTION_PATH = "data/processed/transaction.csv"
BAKERY_PATH = "data/processed/bakery.csv"
DRINK_PATH = "data/processed/drink.csv"
FOOD_PATH = "data/processed/food.csv"

REQUIRED_BASE_COLUMNS = ["Year", "Weekday", "Customer"]
WEEKDAY_NUM_TO_NAME = {
    1: "Monday",
    2: "Tuesday",
    3: "Wednesday",
    4: "Thursday",
    5: "Friday",
}
WEEKDAY_ORDER = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]


def load_category_list(path):
    df = pd.read_csv(path)
    first_col = df.columns[0]
    return df[first_col].dropna().astype(str).str.strip().tolist()


def build_category_map(bakery_items, drink_items, food_items):
    category_map = {}
    for item in bakery_items:
        category_map[item] = "Bakery"
    for item in drink_items:
        category_map[item] = "Drink"
    for item in food_items:
        category_map[item] = "Food"
    return category_map


@st.cache_data
def load_data():
    df = pd.read_csv(TRANSACTION_PATH)
    df.columns = [str(c).strip() for c in df.columns]

    missing = [c for c in REQUIRED_BASE_COLUMNS if c not in df.columns]
    if missing:
        raise ValueError(f"Missing required columns: {missing}")

    item_cols = [c for c in df.columns if c not in REQUIRED_BASE_COLUMNS]
    if not item_cols:
        raise ValueError("No item columns found after Year, Weekday, Customer.")

    df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
    df["Weekday"] = pd.to_numeric(df["Weekday"], errors="coerce")
    df["Customer"] = df["Customer"].astype(str).str.strip()

    for col in item_cols:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)
        df[col] = (df[col] > 0).astype(int)

    df = df.dropna(subset=["Year", "Weekday"]).copy()
    df["Year"] = df["Year"].astype(int)
    df["Weekday"] = df["Weekday"].astype(int)

    df["WeekdayName"] = df["Weekday"].map(WEEKDAY_NUM_TO_NAME)
    df = df.dropna(subset=["WeekdayName"]).copy()
    df["WeekdayName"] = pd.Categorical(df["WeekdayName"], categories=WEEKDAY_ORDER, ordered=True)

    return df, item_cols


try:
    df, item_cols = load_data()
except Exception as e:
    st.error(f"Error loading processed data: {e}")
    st.stop()

bakery_items = load_category_list(BAKERY_PATH)
drink_items = load_category_list(DRINK_PATH)
food_items = load_category_list(FOOD_PATH)
category_map = build_category_map(bakery_items, drink_items, food_items)

with st.sidebar:
    st.header("Filters")
    year_options = sorted(df["Year"].dropna().unique().tolist())
    selected_years = st.multiselect("Select year", options=year_options, default=year_options)

filtered = df[df["Year"].isin(selected_years)].copy()

if filtered.empty:
    st.warning("No data matches the selected year filter.")
    st.stop()

# KPI cards
col1, col2, col3 = st.columns(3)
col1.metric("Rows / Visits", f"{len(filtered):,}")
col2.metric("Unique Customers", f"{filtered['Customer'].nunique():,}")
col3.metric("Available Food Items", f"{len(item_cols):,}")

st.divider()

# -----------------------------
# Sales per Item
# -----------------------------
st.subheader("Sales per Item")
st.caption("Because each item column is coded 1 = purchased, 0 = not purchased, sales here means purchase counts.")

item_sales = filtered[item_cols].sum().reset_index()
item_sales.columns = ["Food Item", "Purchases"]
item_sales["Category"] = item_sales["Food Item"].map(category_map).fillna("Other")
item_sales = item_sales.sort_values("Purchases", ascending=False)

chart1 = (
    alt.Chart(item_sales)
    .mark_bar()
    .encode(
        x=alt.X("Food Item:N", sort="-y", title="Item"),
        y=alt.Y("Purchases:Q", title="Number of Purchases"),
        color=alt.Color("Category:N", title="Food Category"),
        tooltip=["Food Item", "Category", "Purchases"],
    )
    .properties(height=420)
)
st.altair_chart(chart1, use_container_width=True)
st.dataframe(item_sales, use_container_width=True, hide_index=True)

# -----------------------------
# Sales per Category by Weekday and Year
# -----------------------------
st.divider()
st.subheader("Sales per Category by Weekday and Year")

long_df = filtered.melt(
    id_vars=["Year", "Weekday", "WeekdayName", "Customer"],
    value_vars=item_cols,
    var_name="Food Item",
    value_name="Purchase"
)

long_df = long_df[long_df["Purchase"] == 1].copy()
long_df["Category"] = long_df["Food Item"].map(category_map)
long_df = long_df.dropna(subset=["Category"])

cat_summary = (
    long_df.groupby(["Year", "Weekday", "WeekdayName", "Category"], as_index=False)["Purchase"]
    .sum()
)

cat_summary["Year-Weekday"] = (
    cat_summary["Year"].astype(str) + " - " + cat_summary["WeekdayName"].astype(str)
)

chart2 = (
    alt.Chart(cat_summary)
    .mark_bar()
    .encode(
        x=alt.X("Year-Weekday:N", title="Year & Weekday", sort=None),
        y=alt.Y("Purchase:Q", title="Purchases"),
        color=alt.Color("Category:N", title="Food Category"),
        tooltip=["Year", "WeekdayName", "Category", "Purchase"],
    )
    .properties(height=420)
)
st.altair_chart(chart2, use_container_width=True)
st.dataframe(cat_summary, use_container_width=True, hide_index=True)

# -----------------------------
# Customer Purchases
# -----------------------------
st.divider()
st.subheader("Customer Purchases")
search_name = st.text_input("Type a customer name to search", placeholder="Enter customer name")

customer_view = filtered.copy()
if search_name.strip():
    customer_view = customer_view[
        customer_view["Customer"].astype(str).str.contains(search_name.strip(), case=False, na=False)
    ].copy()

if customer_view.empty:
    st.info("No customer entries match the search.")
else:
    def extract_purchased_items(row):
        return [item for item in item_cols if row[item] == 1]

    customer_view["Purchased Items"] = customer_view.apply(extract_purchased_items, axis=1)
    customer_view["Purchased Items"] = customer_view["Purchased Items"].apply(lambda x: ", ".join(x) if x else "")
    customer_view["Total Sales"] = customer_view[item_cols].sum(axis=1)

    customer_display = customer_view[
        ["Customer", "Year", "WeekdayName", "Purchased Items", "Total Sales"]
    ].rename(columns={"WeekdayName": "Weekday"})

    st.dataframe(customer_display, use_container_width=True, hide_index=True)

# -----------------------------
# Regression
# Purchases = a + b*Weekday + c*Category
# -----------------------------
st.divider()
st.subheader("Predicted Sales per Category by Weekday and Year")
st.caption("Linear regression model: Purchases = a + b·Weekday + c·Category")

if cat_summary.empty:
    st.info("No category summary available for regression.")
else:
    reg_df = cat_summary.copy()
    reg_df["Weekday"] = reg_df["Weekday"].astype(str)
    reg_df["Category"] = reg_df["Category"].astype(str)

    y = reg_df["Purchase"]

    X = pd.get_dummies(
        reg_df[["Weekday", "Category"]],
        columns=["Weekday", "Category"],
        drop_first=True
    )

    if len(reg_df) >= 2 and X.shape[1] > 0:
        model = LinearRegression()
        model.fit(X, y)
        reg_df["Predicted"] = pd.Series(model.predict(X), index=reg_df.index).clip(lower=0)
    else:
        reg_df["Predicted"] = y

    reg_df["Year-Weekday"] = (
        reg_df["Year"].astype(str) + " - " + reg_df["WeekdayName"].astype(str)
    )

    actual_bars = (
        alt.Chart(reg_df)
        .mark_bar(opacity=0.75)
        .encode(
            x=alt.X("Year-Weekday:N", title="Year & Weekday", sort=None),
            xOffset=alt.XOffset("Category:N"),
            y=alt.Y("Purchase:Q", title="Actual Purchases"),
            color=alt.Color("Category:N", title="Food Category"),
            tooltip=["Year", "WeekdayName", "Category", "Purchase", "Predicted"]
        )
        .properties(height=420)
    )

    predicted_points = (
        alt.Chart(reg_df)
        .mark_point(filled=True, size=100, color="black")
        .encode(
            x=alt.X("Year-Weekday:N", sort=None),
            xOffset=alt.XOffset("Category:N"),
            y=alt.Y("Predicted:Q", title="Predicted Purchases"),
            tooltip=["Year", "WeekdayName", "Category", "Purchase", "Predicted"]
        )
    )

    st.altair_chart(actual_bars + predicted_points, use_container_width=True)

    regression_output = reg_df[
        ["Year", "WeekdayName", "Category", "Purchase", "Predicted"]
    ].rename(columns={"WeekdayName": "Weekday", "Purchase": "Actual Purchases"})

    st.dataframe(regression_output, use_container_width=True, hide_index=True)

# -----------------------------
# Association Rules
# -----------------------------
st.divider()
st.subheader("Top 20 Association Rules")

try:
    basket = filtered[item_cols].copy().astype(bool)

    if basket.shape[0] < 2:
        st.info("Not enough data for association rule mining.")
    else:
        frequent_itemsets = apriori(basket, min_support=0.01, use_colnames=True)

        if frequent_itemsets.empty:
            st.warning("No frequent itemsets found.")
        else:
            rules = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.01)

            if rules.empty:
                st.warning("No association rules found.")
            else:
                rules["antecedents"] = rules["antecedents"].apply(lambda x: ", ".join(list(x)))
                rules["consequents"] = rules["consequents"].apply(lambda x: ", ".join(list(x)))

                rules_display = rules[
                    ["antecedents", "consequents", "support", "confidence", "lift"]
                ].sort_values(by="lift", ascending=False)

                st.dataframe(rules_display.head(20), use_container_width=True, hide_index=True)
except Exception as e:
    st.error(f"Association rule mining error: {e}")

# -----------------------------
# Customer Segmentation
# -----------------------------
st.divider()
st.subheader("Customer Segmentation")

try:
    customer_matrix = filtered.groupby("Customer")[item_cols].sum()

    if customer_matrix.shape[0] < 2:
        st.info("Not enough customers for clustering.")
    else:
        X_cluster = customer_matrix.div(customer_matrix.sum(axis=1), axis=0).fillna(0)

        n_clusters = st.slider("Number of clusters", 2, 10, 3)

        kmeans = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
        labels = kmeans.fit_predict(X_cluster)

        customer_matrix["Cluster"] = labels

        st.subheader("Customer Clusters")
        st.dataframe(customer_matrix.reset_index(), use_container_width=True)

        cluster_counts = customer_matrix["Cluster"].value_counts().reset_index()
        cluster_counts.columns = ["Cluster", "Count"]

        cluster_chart = (
            alt.Chart(cluster_counts)
            .mark_bar()
            .encode(
                x="Cluster:O",
                y="Count:Q",
                tooltip=["Cluster", "Count"]
            )
        )
        st.altair_chart(cluster_chart, use_container_width=True)

        profile = customer_matrix.groupby("Cluster")[item_cols].mean()
        st.subheader("Cluster Profiles (average purchases)")
        st.dataframe(profile, use_container_width=True)

        st.subheader("Sales by Item for Selected Cluster")
        cluster_options = sorted(customer_matrix["Cluster"].unique().tolist())
        selected_cluster = st.selectbox("Choose a cluster", options=cluster_options)

        cluster_customers = customer_matrix[customer_matrix["Cluster"] == selected_cluster]

        if cluster_customers.empty:
            st.info("No customers in this cluster.")
        else:
            long_cluster = (
                cluster_customers[item_cols]
                .reset_index()
                .melt(id_vars="Customer", var_name="Item", value_name="Purchases")
            )
            long_cluster = long_cluster[long_cluster["Purchases"] > 0]

            if long_cluster.empty:
                st.info("No purchases in this cluster.")
            else:
                cluster_item_chart = (
                    alt.Chart(long_cluster)
                    .mark_bar()
                    .encode(
                        x=alt.X("Item:N", sort="-y", title="Item"),
                        y=alt.Y("Purchases:Q", title="Purchases"),
                        color=alt.Color("Customer:N", title="Customer"),
                        tooltip=["Customer", "Item", "Purchases"]
                    )
                    .properties(height=420)
                )
                st.altair_chart(cluster_item_chart, use_container_width=True)

        # -----------------------------
        # Recommendation
        # -----------------------------
        st.divider()
        st.subheader("Item Recommendation")
        st.caption("Recommend 5 items based on the customer's cluster.")

        customer_options = sorted(customer_matrix.index.tolist())
        selected_customer = st.selectbox("Choose a customer for recommendation", options=customer_options)

        customer_cluster = customer_matrix.loc[selected_customer, "Cluster"]
        st.write(f"**Customer:** {selected_customer}")
        st.write(f"**Assigned Cluster:** {customer_cluster}")

        cluster_data = customer_matrix[customer_matrix["Cluster"] == customer_cluster].copy()
        cluster_item_sales = cluster_data[item_cols].sum()

        adjusted_sales = cluster_item_sales.replace(0, 0.1)

        recommendation_df = adjusted_sales.reset_index()
        recommendation_df.columns = ["Item", "Adjusted Cluster Sales"]
        recommendation_df["Probability"] = (
            recommendation_df["Adjusted Cluster Sales"] / recommendation_df["Adjusted Cluster Sales"].sum()
        )

        if "sampled_items" not in st.session_state:
            st.session_state.sampled_items = None
        if "last_customer" not in st.session_state:
            st.session_state.last_customer = None

        def sample_items():
            n_recommend = min(5, len(recommendation_df))
            sampled = np.random.choice(
                recommendation_df["Item"],
                size=n_recommend,
                replace=False,
                p=recommendation_df["Probability"]
            )
            st.session_state.sampled_items = list(sampled)

        if st.session_state.last_customer != selected_customer:
            st.session_state.sampled_items = None
            st.session_state.last_customer = selected_customer

        if st.session_state.sampled_items is None:
            sample_items()

        if st.button("Sample Again"):
            sample_items()

        sampled_items = st.session_state.sampled_items

        sampled_df = recommendation_df[
            recommendation_df["Item"].isin(sampled_items)
        ].copy()

        sampled_df["Order"] = sampled_df["Item"].apply(lambda x: sampled_items.index(x))
        sampled_df = sampled_df.sort_values("Order").drop(columns="Order")

        st.dataframe(
            sampled_df[["Item", "Adjusted Cluster Sales", "Probability"]],
            use_container_width=True,
            hide_index=True,
        )

        rec_chart = (
            alt.Chart(sampled_df)
            .mark_bar()
            .encode(
                x=alt.X("Item:N", title="Recommended Item"),
                y=alt.Y("Probability:Q", title="Recommendation Probability"),
                tooltip=["Item", "Adjusted Cluster Sales", alt.Tooltip("Probability:Q", format=".3f")],
            )
            .properties(height=350)
        )

        st.altair_chart(rec_chart, use_container_width=True)

except Exception as e:
    st.error(f"Customer segmentation / recommendation error: {e}")
